---
layout : single
title : "2022-04-27-TIL(Dictionary vs Tuple, LocalizedError, 쥬스 메이커 프로젝트 Step1 (3))"
---

# 4월 27일 (수) - Dictionary vs Tuple, LocalizedError, 쥬스 메이커 프로젝트 Step1 (3)

## 🐣 학습내용

> 오늘은 쥬스 메이커 프로젝트 Step1 PR에 대하여 Jake에게 코멘트를 받고, 코멘트를 바탕으로 현재 프로젝트 내 문제점을 개선해보고 또 이를 위한 학습을 하는 시간을 가졌다. 오늘 학습 동안 새롭게 알게된 내용은 `LocalizedError` 이고, 기존에 알고 있던 내용이었지만 더 깊이 들어가 `Dictionary` ,`tuple` 을 비교하였다.
> 

- **Dictionary vs Tuple**
    - 비교
        - `dictionary`는 `array`, `set` 와 더불어 컬렉션 타입에 해당하지만, `tuple`은 컬렉션 타입 X
        - `dictionary`는 `key`와 `value` 2가지 종류의 값을 담을 수 있지만, `tuple`은 그보다 더 많이 
        담을 수 있고, 심지어 `tuple` 내에서는 `function` 타입도 포함 가능
        - `tuple`은 주로 임시적으로 값을 종속시킬 때 사용. 임시가 아닌 존속의 의미로 사용하고자 
        하면 `class`나 `struct`가 적합
        - `tuple`은 순서가 있고, 생성된 이후 변경이 불가능하지만, `dictionary`는 순서가 없으며, 생성 
        이후에도 값의 변경 가능
        - ...
    
- **LocalizedError**
    - 기능 : 오류 및 발생 이유를 설명하는 지역화된 메시지를 제공하는 특수 오류
    - 선언 :
        
        ```swift
        protocol LocalizedError
        ```
        
    - Instance Property :
        
        ```swift
        var errorDescription: String?
        // Required. Default implementation provided.
        
        var failureReason: String?
        // Required. Default implementation provided.
        
        var helpAnchor: String?
        // Required. Default implementation provided.
        
        var recoverySuggestion: String?
        // Required. Default implementation provided.
        ```
        
        > `LocalizedError` 를 활용하여 기존의 `extension` 을 통해 저장 프로퍼티 변수를 할당하여 에러 메시지를 할당한 방식에서 벗어나, `errorDescription` 변수를 생성하여 각각의 에러 경우에 대하여 `NSLocalizedString` 을 통해 메시지를 남기고 `return` 하였다. 해당 작업을 아래의 코드를 통해 확인해본다.
        > 
        
        - 코드
        
        ```swift
        import Foundation
        
        enum FruitStoreError: Error {
            case missingProduct
            case outOfStock
            case invalidAmount
        }
        
        extension FruitStoreError: LocalizedError {
            public var errorDescription: String? {
                switch self {
                case .missingProduct:
                    return NSLocalizedString("해당 상품이 없습니다", comment: "Description of missing Product")
                case .outOfStock:
                    return NSLocalizedString("재고가 부족합니다", comment: "Description of out of stock")
                case .invalidAmount:
                    return NSLocalizedString("잘못된 수량입니다", comment: "Description of invalid amount")
                }
            }
        }
        ```
        
        > `LocalizedError`를 출력하기 위해서는 아래와 같이 `.localizedDescription` 로 호출을 하는 것이 편리하다. `.localizedDescription` 는 `String` 데이터 타입으로 가져오기 때문에 옵셔널 추출 없이 바로 사용할 수 있지만 `.errorDescription` 는 `String?`  데이터 타입으로 가져오기 때문에 옵셔널 추출이 필요하다.
        > 
        
        - 코드
        
        ```swift
        func handle(_ error: Error) {
            switch error {
            case FruitStoreError.outOfStock:
                print(FruitStoreError.outOfStock.localizedDescription)
            case FruitStoreError.missingProduct:
                print(FruitStoreError.missingProduct.localizedDescription)
            case FruitStoreError.invalidAmount:
                print(FruitStoreError.invalidAmount.localizedDescription)
            default:
                print("알 수 없는 오류입니다")
            }
        }
        ```
        
    

## 🐥 문제점 / 고민한 점

<aside>
💡 **실험 1 : 기능 분리 논리 설정 고민(재고 확인 함수 위치 관련)**

</aside>

> 쥬스 메이커 프로젝트 Step1 도중 `Struct` 내부에서 `make()` 함수는 어제의 작업을 통하여 어느정도 정리를 할 수는 있었다. 하지만, 과연 `JuiceMaker` `struct` 안에 재고를 확인하는 것이 바람직한 지, 아니면 `FruitStore` `class` 에서 재고를 확인하는 것이 바람직한 지 고민이 생겼다.
> 

## 🐓 해결방법

<aside>
💡 **실험 1 : 기능 분리 논리 설정 고민(재고 확인 함수 위치 관련) - FruitStore class 내 구현**

</aside>

> 고민 결과, `JuiceMaker` 구조체는 `juice`를 만드는 기능에 집중하면 됨을 깨달았다. 즉, 쥬스를 만들기 위하여 재료가 있는지 정도만 캡슐화를 이용하여 수행하고, 재료가 있는지 재고에 직접 확인하는 작업은 `FruitStore` 클래스 내에서 확인하는 것이 바람직하다 판단되었다. 이에, `JuiceMaker`의 `make()` 함수 내에는 과일의 종류가 있는지 확인하고, 과일의 종류가 있다면 주문할 과일쥬스에 필요한 개수만큼 있는지 확인한 이후 하나의 조건이라도 어긋난다면 `handle()` 함수를 통하여 에러 메시지를 출력하는 기능을 다음과 같이 구현해보았다.
> 

- JuiceMaker 코드

```swift
struct JuiceMaker {
    let juiceMakerStore = FruitStore()
    
    func make(_ juice: Product) {
        do {
            try checkMaterial(juice)
            try checkPossibilityOfMaking(juice)
        } catch (let error) {
            juiceMakerStore.handle(error)
        }
    }
    
    private func checkMaterial(_ juice: Product) throws {
        try juiceMakerStore.goToWarehouse(of: juiceMakerStore.check(fruit:), juice: juice)
    }
    
    private func checkPossibilityOfMaking(_ juice: Product) throws {
        try juiceMakerStore.checkStock(function: juiceMakerStore.reduceStock(fruit:amount:), juice: juice)
    }
}
```

- FruitStore 코드

```swift
class FruitStore {
		...
    func goToWarehouse(of function: (Fruit) throws -> Void, juice: Product) rethrows {
        switch juice {
        case Product.strawberryJuice:
            try function(Fruit.strawberry)
        case Product.bananaJuice:
            try function(Fruit.banana)
        case Product.kiwiJuice:
            try function(Fruit.kiwi)
        case Product.pineappleJuice:
            try function(Fruit.pineapple)
        case Product.strawberryBananaJuice:
            try function(Fruit.strawberry)
            try function(Fruit.banana)
        case Product.mangoJuice:
            try function(Fruit.mango)
        case Product.mangoKiwiJuice:
            try function(Fruit.mango)
            try function(Fruit.kiwi)
        }
    }
    
    func checkStock(function: (Fruit, Int) throws -> Void, juice: Product) rethrows {
        switch juice {
        case Product.strawberryJuice:
            try function(Fruit.strawberry, CostOfJuiceProduction.strawberryInStrawberryJuice)
        case Product.bananaJuice:
            try function(Fruit.banana, CostOfJuiceProduction.bananaInBananaJuice)
        case Product.kiwiJuice:
            try function(Fruit.kiwi, CostOfJuiceProduction.kiwiInKiwiJuice)
        case Product.pineappleJuice:
            try function(Fruit.pineapple, CostOfJuiceProduction.pineappleInPineappleJuice)
        case Product.strawberryBananaJuice:
            try function(Fruit.strawberry, CostOfJuiceProduction.strawberryInStrawberryBananaJuice)
            try function(Fruit.banana, CostOfJuiceProduction.bananaInStrawberryBananaJuice)
        case Product.mangoJuice:
            try function(Fruit.mango, CostOfJuiceProduction.mangoInMangoJuice)
        case Product.mangoKiwiJuice:
            try function(Fruit.mango, CostOfJuiceProduction.mangoInMangoKiwiJuice)
            try function(Fruit.kiwi, CostOfJuiceProduction.kiwiInMangoKiwiJuice)
        }
    }
    
    func handle(_ error: Error) {
        switch error {
        case FruitStoreError.outOfStock:
            print(FruitStoreError.outOfStock.localizedDescription)
        case FruitStoreError.missingProduct:
            print(FruitStoreError.missingProduct.localizedDescription)
        case FruitStoreError.invalidAmount:
            print(FruitStoreError.invalidAmount.localizedDescription)
        default:
            print("알 수 없는 오류입니다")
        }
    }
}
```

> 정리하자면, `FruitStore` 내에서 과일의 종류가 있는지 확인은 물론 (`Fruit` 열거형 내의 `case` 만을 다루지만) `checkMaterial()` 함수 내 `guard` 구문을 이용하여 과일의 종류가 있는지 확인을 하였고, 과일의 종류가 있다면 주문할 과일주스에 필요한 개수만큼 있는지 확인하는 기능은 `checkPossibilityOfMaking()` 함수를 통해 식별해보았다.
> 

> 추가로, do-try-catch 문 이외에 에러메시지를 출력할 수 있는 방법에 대하여 알아보았지만 try?, try!는 각각 에러 발생시 nil 값으로 반환하거나 런타임 에러가 나기 때문에 에러메시지 출력에는 적합하지 않았다. 추가적으로 이를 탐구해보아도 지금은 do-try-catch 이외에는 에러메시지를 출력하는 또 다른 방법은 없다고 판단된다.
> 

## 🌐 참조

1. LocalizedError - Apple Developer Documentation

[Apple Developer Documentation](https://developer.apple.com/documentation/foundation/localizederror)

1. Tuple - Zeddios Tistory

[Swift ) tuple](https://zeddios.tistory.com/238)
